### ISSUE TITLE
Plugin (still) fails to work with Composer < 2.3

### ISSUE THREAD

**Issue by cs278** [bamarni/composer-bin-plugin#134]
Executing `composer bin all install` with Composer 2.2 fails as due to f0b48b5b4fbc13a49bc0d462ec518e27c1ed4ba8 and other changes.

```
PHP Fatal error:  Uncaught Error: Undefined class constant 'SUCCESS' in /tmp/tmp.iXBtOtyjej/vendor/bamarni/composer-bin-plugin/src/Command/BinCommand.php:161
Stack trace:
#0 /tmp/tmp.iXBtOtyjej/vendor/bamarni/composer-bin-plugin/src/Command/BinCommand.php(133): Bamarni\Composer\Bin\Command\BinCommand->executeAllNamespaces('/tmp/tmp.iXBtOt...', 'vendor-bin', Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///usr/local/lib/composer-2.2.14/vendor/symfony/console/Command/Command.php(245): Bamarni\Composer\Bin\Command\BinCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/lib/composer-2.2.14/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/lib/composer-2.2.14/vendor/symfony/console/Application.php(185): S in /tmp/tmp.iXBtOtyjej/vendor/bamarni/composer-bin-plugin/src/Command/BinCommand.php on line 161
```

**Comment by theofidry** [comment]
Thanks for the report! Closed by #137
